// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbsqlpfkjnertkeqwfdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpic3FscGZram5lcnRrZXF3ZmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NzY2ODUsImV4cCI6MjA2NjA1MjY4NX0.lvC1LV4qvxt0-cquEvW5Aq1CADIAwLkkzOoaLoQMwbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});